### ISSUE TITLE
Publish it to Ansible Galaxy!

### ISSUE THREAD

**Issue by b-long** [Asymmetrik/ansible-role-nifi#3]
Hi there @Asymmetrik .  Looks like you've created an excellent Nifi role.  Would you mind publishing it to [Ansible Galaxy](https://galaxy.ansible.com/)?  I see a variety of advantages in doing so, including: 

1. Simplify usage for others
2. Increase adoption (which will increase contributors and potentially lower your maintenance costs)

**Comment by tequalsme** [comment]
Thanks for using! We've been in Galaxy since May: https://galaxy.ansible.com/Asymmetrik/nifi/

**Comment by b-long** [comment]
I'm so sorry about that, clearly user error!  Hadn't found it searching Galaxy earlier.
