### ISSUE TITLE
 copy nifi configs failed

### ISSUE THREAD

**Issue by AhmedSRamadan** [Asymmetrik/ansible-role-nifi#62]
TASK [nifi : copy nifi configs] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
failed: [nifi-node-2] (item={'src': '1.13/nifi.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/nifi.properties'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "/opt/nifi/nifi-current/conf/nifi.properties", "src": "1.13/nifi.properties.j2"}, "msg": "Could not find or access '1.13/nifi.properties.j2'\nSearched in:\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/1.13/nifi.properties.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
failed: [nifi-node-1] (item={'src': '1.13/nifi.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/nifi.properties'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "/opt/nifi/nifi-current/conf/nifi.properties", "src": "1.13/nifi.properties.j2"}, "msg": "Could not find or access '1.13/nifi.properties.j2'\nSearched in:\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/1.13/nifi.properties.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
failed: [nifi-node-3] (item={'src': '1.13/nifi.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/nifi.properties'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "/opt/nifi/nifi-current/conf/nifi.properties", "src": "1.13/nifi.properties.j2"}, "msg": "Could not find or access '1.13/nifi.properties.j2'\nSearched in:\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/roles/nifi/tasks/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/templates/1.13/nifi.properties.j2\n\t/home/ahmed/Desktop/ansible/ansible-role-nifi/1.13/nifi.properties.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
changed: [nifi-node-1] => (item={'src': 'extra-args.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/extra-args.properties'})
changed: [nifi-node-3] => (item={'src': 'extra-args.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/extra-args.properties'})
changed: [nifi-node-2] => (item={'src': 'extra-args.properties.j2', 'dest': '/opt/nifi/nifi-current/conf/extra-args.properties'})

**Comment by rstjohn** [comment]
version 1.13.x was not thoroughly tested and changes were not pushed to GitHub.  the changes were pushed

**Comment by AhmedSRamadan** [comment]
I fixed the issue but service doesn't come up, I will try new push now
